development:
  adapter: postgresql
  encoding: unicode
  database: heroku_postgresql_white_url
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: heroku_postgresql_white_url
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  username: cheshireoctopus
  database: heroku_postgresql_white_url
